#!/usr/bin/env python

import sys
import re

op_total = 0
total_total = 0

regex = re.compile(r'fp32: (\d+)')

op_to_count = None
if len(sys.argv) > 2 and sys.argv[2] == '-n':
    no_barrier = True
else:
    no_barrier = False

with open(sys.argv[1]) as f:
    barrier_found = False
    if not no_barrier:
        while not barrier_found:
            line = next(f)
            barrier_found = 'Barrier' in line

    for line in f:
        if 'rid: 0' in line and (op_to_count is None or op_to_count in line):
            m = regex.search(line)
            op_total += int(m.groups(1)[0])

        if 'rid: 3' in line:
            m = regex.search(line)
            total_total = int(m.groups(1)[0])
            break

print('Op fp32:', op_total)
print('Total fp32:', total_total)

if total_total > 0:
    print('Frac of total:', op_total / total_total)
