#!/usr/bin/env python

import sys
import yaml
import re
import numpy as np

op_total = 0
total_total = 0

regex = re.compile(r'total: (\d+)')

def OpEvents(filename, skip_till_barrier=True, stop_at_infer=True):
    with open(filename) as f:
        if skip_till_barrier:
            barrier_found = False
            while not barrier_found:
                line = next(f)
                barrier_found = 'Barrier' in line

        for line in f:
            if 'rid: 0' in line:
                yield yaml.safe_load(line)[0]

            if 'rid: 3' in line and stop_at_infer:
                break

for (ev1, ev2) in zip(OpEvents(sys.argv[1]), OpEvents(sys.argv[2])):
    total_1 = ev1['total']
    total_2 = ev2['total']

    assert ev1['rname'] == ev2['rname']

    avg = np.average([total_1, total_2])
    pdiff = np.abs(total_1 - total_2) / avg

    print(ev1['rname'], total_1, total_2, pdiff * 100)

